name: findo
description: Simple search field with debounce .
version: 1.0.0
author: Veli Bacik <vbacik.10@gmail.com>
homepage: https://github.com/VB10/findo

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
